// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymension/eibc/demand_order.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DemandOrder_Status int32

const (
	DemandOrder_ACTIVE    DemandOrder_Status = 0
	DemandOrder_FULFILLED DemandOrder_Status = 1
	DemandOrder_CANCELLED DemandOrder_Status = 2
	DemandOrder_EXPIRED   DemandOrder_Status = 3
	DemandOrder_REVERTED  DemandOrder_Status = 4
)

var DemandOrder_Status_name = map[int32]string{
	0: "ACTIVE",
	1: "FULFILLED",
	2: "CANCELLED",
	3: "EXPIRED",
	4: "REVERTED",
}

var DemandOrder_Status_value = map[string]int32{
	"ACTIVE":    0,
	"FULFILLED": 1,
	"CANCELLED": 2,
	"EXPIRED":   3,
	"REVERTED":  4,
}

func (x DemandOrder_Status) String() string {
	return proto.EnumName(DemandOrder_Status_name, int32(x))
}

func (DemandOrder_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3808f42eed32f331, []int{0, 0}
}

type DemandOrder struct {
	// id is a hash of the form generated by GetRollappPacketKey,
	// e.g rollappid/status/packetProofHeight/packetDestinationChannel-PacketSequence which gurantees uniqueness
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// tracking_packet_key is the key of the packet that is being tracked.
	// This key can change depends on the packet status.
	TrackingPacketKey string             `protobuf:"bytes,2,opt,name=tracking_packet_key,json=trackingPacketKey,proto3" json:"tracking_packet_key,omitempty"`
	Price             string             `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Fee               string             `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Denom             string             `protobuf:"bytes,5,opt,name=denom,proto3" json:"denom,omitempty"`
	Recipient         string             `protobuf:"bytes,6,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status            DemandOrder_Status `protobuf:"varint,7,opt,name=status,proto3,enum=dymensionxyz.dymension.eibc.DemandOrder_Status" json:"status,omitempty"`
}

func (m *DemandOrder) Reset()         { *m = DemandOrder{} }
func (m *DemandOrder) String() string { return proto.CompactTextString(m) }
func (*DemandOrder) ProtoMessage()    {}
func (*DemandOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_3808f42eed32f331, []int{0}
}
func (m *DemandOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DemandOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DemandOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DemandOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemandOrder.Merge(m, src)
}
func (m *DemandOrder) XXX_Size() int {
	return m.Size()
}
func (m *DemandOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DemandOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DemandOrder proto.InternalMessageInfo

func (m *DemandOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DemandOrder) GetTrackingPacketKey() string {
	if m != nil {
		return m.TrackingPacketKey
	}
	return ""
}

func (m *DemandOrder) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *DemandOrder) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *DemandOrder) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *DemandOrder) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *DemandOrder) GetStatus() DemandOrder_Status {
	if m != nil {
		return m.Status
	}
	return DemandOrder_ACTIVE
}

func init() {
	proto.RegisterEnum("dymensionxyz.dymension.eibc.DemandOrder_Status", DemandOrder_Status_name, DemandOrder_Status_value)
	proto.RegisterType((*DemandOrder)(nil), "dymensionxyz.dymension.eibc.DemandOrder")
}

func init() { proto.RegisterFile("dymension/eibc/demand_order.proto", fileDescriptor_3808f42eed32f331) }

var fileDescriptor_3808f42eed32f331 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0xdb, 0x02, 0xe5, 0x32, 0xdc, 0x4b, 0x7a, 0x47, 0x16, 0x8d, 0x9a, 0x06, 0x59, 0xb1,
	0x9a, 0x26, 0xfa, 0x04, 0x48, 0x07, 0x25, 0xa2, 0x92, 0x8a, 0xc4, 0xb8, 0x21, 0xa5, 0x33, 0xd6,
	0x09, 0x69, 0xa7, 0x69, 0x87, 0x84, 0xfa, 0x14, 0xbe, 0x92, 0x3b, 0x97, 0x2c, 0x5d, 0x1a, 0x78,
	0x11, 0xd3, 0xa9, 0x02, 0x2b, 0x77, 0xf3, 0x9d, 0xf3, 0xfd, 0x27, 0x73, 0x72, 0xc0, 0x09, 0xc9,
	0x42, 0x1a, 0xa5, 0x8c, 0x47, 0x36, 0x65, 0x33, 0xdf, 0x26, 0x34, 0xf4, 0x22, 0x32, 0xe5, 0x09,
	0xa1, 0x09, 0x8a, 0x13, 0x2e, 0x38, 0x3c, 0xda, 0x2a, 0xcb, 0xec, 0x05, 0x6d, 0x01, 0xe5, 0xfe,
	0x61, 0x33, 0xe0, 0x01, 0x97, 0x9e, 0x9d, 0xbf, 0x8a, 0x48, 0xfb, 0x4d, 0x03, 0x75, 0x47, 0x4e,
	0xba, 0xcd, 0x07, 0xc1, 0x06, 0xd0, 0x18, 0x31, 0xd5, 0x96, 0xda, 0xa9, 0xb9, 0x1a, 0x23, 0x10,
	0x81, 0x03, 0x91, 0x78, 0xfe, 0x9c, 0x45, 0xc1, 0x34, 0xf6, 0xfc, 0x39, 0x15, 0xd3, 0x39, 0xcd,
	0x4c, 0x4d, 0x0a, 0xff, 0x7f, 0x5a, 0x23, 0xd9, 0xb9, 0xa2, 0x19, 0x6c, 0x82, 0x4a, 0x9c, 0x30,
	0x9f, 0x9a, 0x25, 0x69, 0x14, 0x00, 0x0d, 0x50, 0x7a, 0xa2, 0xd4, 0x2c, 0xcb, 0x5a, 0xfe, 0xcc,
	0x3d, 0x42, 0x23, 0x1e, 0x9a, 0x95, 0xc2, 0x93, 0x00, 0x8f, 0x41, 0x2d, 0xa1, 0x3e, 0x8b, 0x19,
	0x8d, 0x84, 0xa9, 0xcb, 0xce, 0xae, 0x00, 0x2f, 0x80, 0x9e, 0x0a, 0x4f, 0x2c, 0x52, 0xb3, 0xda,
	0x52, 0x3b, 0x8d, 0x53, 0x1b, 0xfd, 0xb2, 0x2f, 0xda, 0xdb, 0x0a, 0xdd, 0xc9, 0x98, 0xfb, 0x1d,
	0x6f, 0x5f, 0x03, 0xbd, 0xa8, 0x40, 0x00, 0xf4, 0x6e, 0x6f, 0x3c, 0x98, 0x60, 0x43, 0x81, 0xff,
	0x40, 0xad, 0x7f, 0x3f, 0xec, 0x0f, 0x86, 0x43, 0xec, 0x18, 0x6a, 0x8e, 0xbd, 0xee, 0x4d, 0x0f,
	0x4b, 0xd4, 0x60, 0x1d, 0x54, 0xf1, 0xc3, 0x68, 0xe0, 0x62, 0xc7, 0x28, 0xc1, 0xbf, 0xe0, 0x8f,
	0x8b, 0x27, 0xd8, 0x1d, 0x63, 0xc7, 0x28, 0x9f, 0x5f, 0xbe, 0xaf, 0x2d, 0x75, 0xb5, 0xb6, 0xd4,
	0xcf, 0xb5, 0xa5, 0xbe, 0x6e, 0x2c, 0x65, 0xb5, 0xb1, 0x94, 0x8f, 0x8d, 0xa5, 0x3c, 0xa2, 0x80,
	0x89, 0xe7, 0xc5, 0x0c, 0xf9, 0x3c, 0xb4, 0xf7, 0xff, 0xba, 0x03, 0x7b, 0x59, 0x5c, 0x53, 0x64,
	0x31, 0x4d, 0x67, 0xba, 0x3c, 0xca, 0xd9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0x34, 0x27,
	0xa5, 0xec, 0x01, 0x00, 0x00,
}

func (m *DemandOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DemandOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DemandOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintDemandOrder(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintDemandOrder(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintDemandOrder(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintDemandOrder(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintDemandOrder(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TrackingPacketKey) > 0 {
		i -= len(m.TrackingPacketKey)
		copy(dAtA[i:], m.TrackingPacketKey)
		i = encodeVarintDemandOrder(dAtA, i, uint64(len(m.TrackingPacketKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDemandOrder(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDemandOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovDemandOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DemandOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDemandOrder(uint64(l))
	}
	l = len(m.TrackingPacketKey)
	if l > 0 {
		n += 1 + l + sovDemandOrder(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovDemandOrder(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovDemandOrder(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovDemandOrder(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovDemandOrder(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovDemandOrder(uint64(m.Status))
	}
	return n
}

func sovDemandOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDemandOrder(x uint64) (n int) {
	return sovDemandOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DemandOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDemandOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DemandOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DemandOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemandOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrackingPacketKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemandOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrackingPacketKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemandOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemandOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemandOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDemandOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= DemandOrder_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDemandOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDemandOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDemandOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDemandOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDemandOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDemandOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDemandOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDemandOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDemandOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDemandOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDemandOrder = fmt.Errorf("proto: unexpected end of group")
)
